### ISSUE TITLE
R&D: Create a scenario to test new UBI image with JIB

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/project#21]
## R&D

Finalized the following scenario - https://github.com/halkyonio/container-images/tree/master/sandbox/hal2 to use JIB tool to build a container image, deploy the image on ocp internal docker registry

**NOTE** :  A new release of JIB is needed. See: https://github.com/GoogleContainerTools/jib/issues/2260

**Comment by metacosm** [comment]
This should have been created under the halkyon project, not here.
