### ISSUE TITLE
Spring Cloud Stream

### ISSUE THREAD

**Issue by gytis** [snowdrop/project#34]
Some foundational work has already been done in Smallrye Reactive Messaging and Quarkus

**Comment by cmoulliard** [comment]
Can you discuss with Naina what will be the deliverables about this epic please ? @geoand 
As some developments have been done and delivered, can you then add the issues to this epic please ? @geoand

**Comment by geoand** [comment]
Yup, I added the first issue

**Comment by cmoulliard** [comment]
What are the next steps now that you closed the issue 40 ? @geoand

**Comment by geoand** [comment]
I have added my new estimate for what I think it means if we would like to implement this. If we decide to implement it, then I will take it :)

**Comment by geoand** [comment]
Closing as duplicate
