### ISSUE TITLE
Create and distribute a password-store to hold passwords for the team

### ISSUE THREAD

**Issue by iocanel** [snowdrop/project#4]
Create shared password-store to hold the team passwords.

We are going to follow this [blog post](https://medium.com/@davidpiegza/using-pass-in-a-team-1aa7adf36592) whic provides detailed instructions.

**Comment by cmoulliard** [comment]
@iocanel. I propose to create a git project under the snowdrop group - https://gitlab.cee.redhat.com/snowdrop

**Comment by cmoulliard** [comment]
List of passwords will come from : 
- Team Info doc: https://docs.google.com/document/d/1XL7SHIjVaQZEd2DyYu-Zr1AaC3ht5ajvi1YqhEjQZ_g
- Individual team contributors

**Comment by cmoulliard** [comment]
> It might be better to send them to me via email or zulip.

As soon as the gitlab repo is created then we could share the gpg id using the gitlab repo. Make sense ?

**Comment by iocanel** [comment]
Sure.

**Comment by cmoulliard** [comment]
Can you update the ticket please ?
Questions : 
- Is the document to use it finalized and shared with the team ? 
- How should we backup the GPG keys if they should be used on a new, another laptop ?
- Is it documented the comvention to follow to add keys ?
- Can you schedule a 15-20 min meeting to show to the team how to install, us it please ?
- Should we use it with LastPass ? 
@iocanel

**Comment by iocanel** [comment]
@cmoulliard: I will document what is missing.

I don't feel that its mandatory, maybe we should just provide some pointers to users that want to.

**Comment by cmoulliard** [comment]
> I don't feel that its mandatory, maybe we should just provide some pointers to users that want to.

That should be part of the team doc

**Comment by iocanel** [comment]
Doc has been added.
